name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.USER_DOCKER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build docker image
      run: |
        docker build -t edgarjoaquin1102/docker-astro:0.0.2 .

    - name: Push to docker hub
      run: |
        docker push edgarjoaquin1102/docker-astro:0.0.2


    
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    
